# ─────────────────────────────────────────────────────────────────────────────
#  LazyVM.Defaults.psd1 - every setting Build-LazyVM.ps1 uses, with its default
#
#  DO NOT EDIT THIS FILE. It is replaced whenever the script is updated.
#  To change a setting, copy LazyVM.Config.example.psd1 to LazyVM.Config.psd1
#  in this folder and set your value there. Only the settings you list in that
#  file change; everything else keeps the default below.
#
#  This is a data-only file: PowerShell refuses to run any code in it, so it
#  may contain only text, numbers, $true/$false, lists @() and tables @{}.
#
#  HOST PATHS are relative to the root folder (see Root below), so 'VMs' means
#  <root>\VMs. A full path such as 'E:\VMs' is used exactly as written, which
#  is how one large item can be put on another drive. Paths inside the guest
#  (GuestSetupDir, GuestSqlDataDir and the like) are not affected.
#
#  SEVERAL VMs: each VM has a profile, Config\VMs\<Name>\VM.psd1, applied after
#  this file and LazyVM.Config.psd1. {VM} in any setting below is replaced by
#  the VM's name, which is how each VM gets its own disks, state, log,
#  credentials and scheduled task. Create a VM's profile with -NewVM.
# ─────────────────────────────────────────────────────────────────────────────
@{
    # ── Root folder ─────────────────────────────────────────────────────────
    # Every host path below lives under this folder. Leave it empty to use the
    # folder above the one holding Build-LazyVM.ps1: with the script in
    # D:\DevVM\Scripts, the root is D:\DevVM. The -Root parameter, when given,
    # takes precedence over this setting. Must be a folder on a local drive.
    #
    # Moving the root after the first build means moving its contents too (the
    # VM disks, the credential key and the captured state live under it) and
    # registering the scheduled task again.
    Root              = ''

    # The VM's configuration and OS disk go in <VHDXRoot>\<VM name>.
    VHDXRoot          = 'VMs'
    OSDiskSizeGB      = 120
    vCPU              = 4
    # 8 GB startup rather than 4: ReFS uses more memory than NTFS, and 8 GB is
    # Microsoft's stated minimum for Dev Drive (16 GB recommended). Dynamic
    # memory still releases it when the guest is idle.
    MemStartGB        = 8
    MemMinGB          = 2
    MemMaxGB          = 16

    ISOPath           = 'ISO\Win11Ent_Eval.iso'
    ISOMinSizeGB      = 4
    ISOSearchRoot     = 'ISO'
    ISODownloadPage   = 'https://www.microsoft.com/en-us/evalcenter/evaluate-windows-11-enterprise'

    SQLInstallerPath  = 'Installers\SQLServer2022-x64-ENU-Dev.exe'
    SQLInstallerUrl   = 'https://go.microsoft.com/fwlink/p/?linkid=2215158&clcid=0x409&culture=en-us&country=US'
    SQLMinSizeMB      = 1

    SQLDiskPath       = 'SQLDisk\{VM}.vhdx'
    SQLDiskSizeGB     = 100

    # ── Dev Drive ───────────────────────────────────────────────────────────
    # A ReFS volume with a per-machine "trusted" designation, giving Defender
    # performance mode and ReFS block cloning for build workloads.
    #
    # The VHDX lives HERE, on the host, and is attached to the VM as a second
    # disk — exactly like the SQL data disk, and for the same reason: a rebuild
    # never touches it. Do NOT use the guest's Settings > Create Dev Drive >
    # "Create new VHD" flow instead; that puts the VHD inside the guest's C:,
    # which is the disk a rebuild deletes.
    #
    # Trust is stored per machine and does not travel with the file, so after a
    # rebuild the volume returns as plain ReFS and Phase 7 re-trusts it. That
    # is a metadata operation: the data is not touched.
    UseDevDrive       = $true
    DevDrivePath      = 'DevDrive\{VM}.vhdx'
    DevDriveSizeGB    = 250        # minimum supported by Dev Drive is 50
    DevDriveLetter    = 'W'
    DevDriveLabel     = 'DevDrive'

    # Extra minifilters permitted to attach to the Dev Drive. Everything except
    # antivirus is detached by default, which is where the speed comes from.
    # 'PrjFlt' for VFS/Live Unit Testing, 'WinSetupMon' if TEMP is redirected
    # onto the drive, 'bindFlt, wcifs' for containers.
    DevDriveFilters   = @()

    # Enhanced Session Mode carries clipboard and file transfer over the VMBus
    # rather than the network, so it needs no network setup at all.
    EnableEnhancedSession = $true

    SeedDiskPath      = 'VMs\{VM}-Seed.iso'

    # Where manual Hyper-V checkpoints of the VM are stored. Automatic
    # checkpoints are turned off.
    CheckpointDir     = 'Checkpoints\{VM}'

    VSSettingsBackup  = 'Backup\{VM}\VisualStudio.vssettings'
    LogFile           = 'Logs\{VM}.log'
    LogMaxSizeMB      = 5

    # Switch used by the VM. 'Default Switch' is managed by Windows: it
    # provides NAT and DHCP automatically, and its address range CANNOT be set
    # — Windows assigns it.
    SwitchName        = 'Default Switch'

    # FALLBACK ONLY. These three are used if, and only if, SwitchName above
    # does not exist, in which case the script creates an internal switch plus
    # a NAT network at these addresses (New-VMSwitch has no NAT switch type;
    # NAT is configured separately with New-NetNat). While 'Default Switch'
    # exists and is in use, these values are deliberately ignored.
    NatSwitchName     = 'LazyVM-NAT'
    NatSubnet         = '192.168.180.0/24'
    NatHostIP         = '192.168.180.1'

    # Default only. Replaced at run time by -GuestUser, or by the account
    # stored with -SetupCredentials.
    GuestAdminUser    = 'devadmin'
    GuestComputerName = '{VM}'
    GuestTimeZone     = 'Pacific Standard Time'
    GuestSetupDir     = 'C:\LazyVMSetup'

    # Preferred letter for the SQL data disk. If it is already taken in the
    # guest (a Generation 2 VM's DVD drive usually claims D:), the script moves
    # an optical drive aside, or falls back to another letter and rewrites the
    # four paths below to match. Nothing downstream hard-codes D:.
    GuestDataDriveLetter = 'D'
    SqlDataFolder     = 'SQLData'
    SqlLogFolder      = 'SQLLog'
    SqlTempFolder     = 'SQLTemp'
    SqlBackupFolder   = 'SQLBackup'

    # Defaults; recomputed by Set-GuestSqlPaths once the real letter is known.
    GuestSqlDataDir   = 'D:\SQLData'
    GuestSqlLogDir    = 'D:\SQLLog'
    GuestSqlTempDir   = 'D:\SQLTemp'
    GuestSqlBackupDir = 'D:\SQLBackup'

    # ── What gets installed ─────────────────────────────────────────────────
    # Each VM is built from its tooling list, Config\VMs\<Name>\Tooling.json,
    # which the daily maintenance run keeps up to date with what is actually
    # installed in the guest (see Tooling tracking below). A VM with no list
    # yet is built from Config\Tooling.Default.json.
    #
    # Visual Studio Installer products (Visual Studio, SSMS) are installed from
    # the bootstrapper for their channel. {edition} becomes the edition, lower
    # case: Microsoft.VisualStudio.Product.Community -> vs_community.exe. Add a
    # line here for any other channel a tooling list uses.
    InstallerBootstrappers = @{
        'VisualStudio.18.Release' = 'https://aka.ms/vs/stable/vs_{edition}.exe'
        'VisualStudio.18.Stable'  = 'https://aka.ms/vs/stable/vs_{edition}.exe'
        'VisualStudio.18.Insiders' = 'https://aka.ms/vs/insiders/vs_{edition}.exe'
        'VisualStudio.17.Release' = 'https://aka.ms/vs/17/release/vs_{edition}.exe'
        'SSMS.22.SSMS.Release'    = 'https://aka.ms/ssms/22/release/vs_SSMS.exe'
    }

    # Application settings carried across a rebuild: each registry key is
    # exported by a capture and imported by a restore, after the application
    # itself has been reinstalled from the tooling list.
    AppSettings       = @(
        @{ Name = 'WinMerge'; RegistryKey = 'HKCU\Software\Thingamahoochie\WinMerge' }
    )

    # Phase 8b: move an existing instance's user databases and tempdb onto the
    # data disk. Files are copied and verified before the originals go, and any
    # failure rolls back to the original location. master/model/msdb are never
    # touched. Set to $false to leave an existing instance exactly where it is.
    MoveSqlDataToDataDisk = $true

    CredStoreDir      = 'Backup'
    CredKeyFile       = 'Backup\.lazyvm.key'
    GuestCredFile     = 'Backup\{VM}\guest.cred'

    # ── Rebuild-on-expiry ───────────────────────────────────────────────────
    # Captured guest state lives here, on the host, and no rebuild touches it.
    StateDir          = 'State\{VM}'
    CertCredFile      = 'Backup\{VM}\certs.cred'

    # Act this many days before the evaluation expires. The maintenance task
    # runs daily and does nothing until the licence gets this close.
    RebuildThresholdDays = 10

    # Keep the retired OS disk after a verified rebuild? $false deletes it and
    # reclaims the space; $true keeps every generation, which adds up fast.
    DeleteRetiredDiskOnSuccess = $true

    # Guest folders captured and carried across a rebuild. The Dev Drive needs
    # none of this: it persists across rebuilds on its own.
    GuestProjectPaths = @(
        '%USERPROFILE%\source\repos'
        '%USERPROFILE%\Documents'
        '%USERPROFILE%\Desktop'
        '%USERPROFILE%\.ssh'
    )
    ProjectExcludeDirs = @('bin', 'obj', 'node_modules', 'packages', '.vs', 'TestResults', '.git')
    MaxProjectCaptureGB = 20
    GuestRestoreRoot  = '%USERPROFILE%\source'

    # Prefix for this script's own guest artefacts, excluded from capture so a
    # rebuild does not drag its own scaffolding along.
    ExcludeTaskPrefix = 'LazyVM-'

    ResumeRegKey      = 'HKLM:\SOFTWARE\LazyVM\{VM}'
    ResumeTaskName    = 'LazyVM-ResumeAfterReboot-{VM}'
    ScheduleTaskName  = 'LazyVM-Maintain-{VM}'

    # ── Tooling tracking ─────────────────────────────────────────────────────
    # The daily maintenance run records what is installed in the guest in
    # Config\VMs\<Name>\Tooling.json. When that changes, it takes a Hyper-V
    # checkpoint first and then records the change, so every recorded version
    # can be returned to with -Revert. A checkpoint covers ALL of the VM's
    # disks, including the Dev Drive and the SQL data disk.
    #
    # How many of these checkpoints to keep; older ones are removed.
    ToolingCheckpointsToKeep = 3

    # How many days of daily copies of the tooling list to keep.
    ToolingHistoryDays = 30

    # winget packages never recorded: ones that come with Windows, and the
    # products the Visual Studio Installer manages (recorded separately, with
    # their workloads). Wildcards allowed. A list in LazyVM.Config.psd1
    # replaces this one, so copy it and add to it.
    ToolingWingetExclude = @(
        'Microsoft.VisualStudio.*'
        'Microsoft.Edge'
        'Microsoft.Teams'
        'Microsoft.Outlook'
        'Microsoft.OneDrive'
        'Microsoft.365Copilot'
        'Microsoft.AppInstaller'
        'Microsoft.UI.Xaml.*'
        'Microsoft.VCLibs.*'
        'Microsoft.WindowsAppRuntime.*'
        'Microsoft.DotNet.Native.Runtime'
        'XP9CXNGPPJ97XX'
    )

    # winget ids to check for directly, for packages winget can match but
    # leaves out of its export, so they are still recorded (and reinstalled)
    # as winget packages. Checked with: winget list --id <id> --exact
    ToolingWingetCheck = @()

    # When the VM's daily maintenance task runs (24-hour HH:mm, host time).
    # -NewVM sets each new VM an hour after the latest existing one, so two
    # VMs are never maintained at the same time.
    MaintenanceTime   = '02:00'

    GuestWaitMinutes  = 90     # OS install + OOBE can legitimately take this long

    # PowerShell Direct works over the VMBus with no network at all, so the
    # guest reports as reachable well before DNS is up. Anything that needs to
    # download waits this long for the network first.
    GuestNetworkWaitMinutes = 10
    # Time limit for installing each Visual Studio Installer product.
    VSInstallMinutes  = 90
    SQLInstallMinutes = 60
}
